filter:
  excluded_paths: [tests/*]

checks:
  php: true

tools:
  external_code_coverage: true

build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run
