version: 2

references:
  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  results_root: &results_root
    /tmp/results

  attach_results: &attach_results
    attach_workspace:
      at: *results_root

  composer: &composer
    run:
      name: Install composer dependencies
      command: composer update --prefer-lowest --no-interaction

  load_code: &load_code
    run:
      name: load code from workspace
      command: |
        # Move all files and dotfiles to current directory
        mv /tmp/workspace/courier/* /tmp/workspace/courier/.[!.]* .

  report_results: &report_results
    store_test_results:
      path: reports

  store_results: &store_results
    store_artifacts:
      path: *results_root
      destination: test_reports/

  push_coverage: &push_coverage
    run:
      name: Push the coverage reports to Codecov
      command: |
        bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'

jobs:
  checkout_code:
    working_directory: /home/circleci/courier
    docker:
      - image: notnoopci/php:5.6
    steps:
      - checkout
      - run:
          name: Copy checkout to workspace
          command: |
            mkdir -p /tmp/workspace/courier
            mv * .[!.]* /tmp/workspace/courier/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - courier

  php71:
    working_directory: /home/circleci/courier
    docker:
      - image: notnoopci/php:7.1
    steps:
      - *attach_workspace
      - *load_code
      - *composer
      - run:
          name: Run tests
          command: |
            # Ensure xdebug is installed
            sudo sh .circleci/enable_xdebug.sh
            sh .circleci/test.sh 71
      - *report_results
      - *store_results
      - *push_coverage

workflows:
  version: 2

  build_and_test:
    jobs:
      - checkout_code
      - php71:
          requires:
            - checkout_code
