# Site settings
title: Courier
owner: Quartzy
email: opensource@quartzy.com
description: >
  Courier is a PHP library for delivering emails using a simple interface
  and domain objects.

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://github.com/quartzy/courier # the base hostname & protocol for your site
git_address: https://github.com/quartzy/courier
git_edit_address: https://github.com/quartzy/courier

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: America/Los_Angeles
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
